config:
  host: devx-helloworld-springboot-0o905.nonp-dev-4.use1.eng-nonprod.flexport.internal
  namespace: devx-helloworld-springboot-0o905-dev
  image:
    name: artifactory.flexport.io/devx-helloworld-springboot-0o905-docker-dev-local/devx-helloworld-springboot-0o905
    tag: 0.0.1-SNAPSHOT
